config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "cars#index"
  resources :cars, only: %i[index new create show edit]
  resources :documents, only: %i[]
  resources :parts, only: %i[]
  resources :services, only: %i[]
  resources :shop_visits, only: %i[]
  resources :shops, only: %i[]
end

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        cars#index
#                                  cars GET    /cars(.:format)                                                                          cars#index
#                               new_car GET    /cars/new(.:format)                                                                      cars#new
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id            :bigint           not null, primary key
#  cost          :float
#  description   :string
#  notes         :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  part_id       :bigint           not null
#  shop_visit_id :bigint           not null
#
# Indexes
#
#  index_services_on_part_id        (part_id)
#  index_services_on_shop_visit_id  (shop_visit_id)
#
# Foreign Keys
#
#  fk_rails_...  (part_id => parts.id)
#  fk_rails_...  (shop_visit_id => shop_visits.id)
#

class Service < ApplicationRecord
  belongs_to :part
  belongs_to :shop_visit
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show; end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit; end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: "Service was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: "Service was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: "Service was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def service_params
    params.require(:service).permit(:cost, :description, :notes, :part_id, :shop_visit_id)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Service #<%= service.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Cost</dt>
      <dd><%= service.cost %></dd>

      <dt>Description</dt>
      <dd><%= service.description %></dd>

      <dt>Notes</dt>
      <dd><%= service.notes %></dd>

      <dt>Part</dt>
      <dd><%= service.part %></dd>

      <dt>Shop visit</dt>
      <dd><%= service.shop_visit %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back service, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_service_url(service), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to service, method: :delete, data: { confirm: "Do you really want to delete this service?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(service.updated_at) %> ago
  </div>
</div>

app/views/services/_form.html.erb
<% was_validated = service.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(service, html: form_html_options) do |f| %>
  <div class="form-group">
    <% cost_class = "form-control" %>
    <% cost_was_invalid = service.errors.include?(:cost) %>

    <% if was_validated %>
      <% if cost_was_invalid %>
        <% cost_class << " is-invalid" %>
      <% else %>
        <% cost_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cost %>

    <%= f.text_field :cost, class: cost_class, placeholder: "Enter cost" %>
    <% if cost_was_invalid %>
      <% service.errors.full_messages_for(:cost).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = service.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>

    <%= f.text_field :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% service.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% notes_class = "form-control" %>
    <% notes_was_invalid = service.errors.include?(:notes) %>

    <% if was_validated %>
      <% if notes_was_invalid %>
        <% notes_class << " is-invalid" %>
      <% else %>
        <% notes_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :notes %>

    <%= f.text_area :notes, class: notes_class, placeholder: "Enter notes" %>
    <% if notes_was_invalid %>
      <% service.errors.full_messages_for(:notes).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% part_class = "form-control" %>
    <% part_was_invalid = service.errors.include?(:part) %>

    <% if was_validated %>
      <% if part_was_invalid %>
        <% part_class << " is-invalid" %>
      <% else %>
        <% part_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :part %>

    <%= f.text_field :part, class: part_class, placeholder: "Enter part" %>
    <% if part_was_invalid %>
      <% service.errors.full_messages_for(:part).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% shop_visit_class = "form-control" %>
    <% shop_visit_was_invalid = service.errors.include?(:shop_visit) %>

    <% if was_validated %>
      <% if shop_visit_was_invalid %>
        <% shop_visit_class << " is-invalid" %>
      <% else %>
        <% shop_visit_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :shop_visit %>

    <%= f.text_field :shop_visit, class: shop_visit_class, placeholder: "Enter shop visit" %>
    <% if shop_visit_was_invalid %>
      <% service.errors.full_messages_for(:shop_visit).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/services/_list_item.html.erb
<%= link_to service, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Service #<%= service.id %>

    <small class="text-muted">
      <%= time_ago_in_words(service.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/services/_table_row.html.erb
<tr>
  <td>
    <%= service.cost %>
  </td>

  <td>
    <%= service.description %>
  </td>

  <td>
    <%= service.notes %>
  </td>

  <td>
    <%= service.part %>
  </td>

  <td>
    <%= service.shop_visit %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to service, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_service_url(service), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to service, method: :delete, data: { confirm: "Do you really want to delete this service?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/services/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Service #<%= @service.id %>
      </h2>

      <div class="card-body">
        <%= render "form", service: @service %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Services

      <%= link_to new_service_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Cost
            </th>

            <th>
              Description
            </th>

            <th>
              Notes
            </th>

            <th>
              Part
            </th>

            <th>
              Shop visit
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @services, partial: "table_row", as: :service %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @services.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :service %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Services

        <%= link_to new_service_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @services, partial: "list_item", as: :service %>
      </div>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Service
      </h2>

      <div class="card-body">
        <%= render "form", service: @service %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @service, partial: "card", as: :service %>
  </div>
</div>