config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "cars#index"
  resources :cars, only: %i[index new create show edit]
  resources :documents, only: %i[]
  resources :parts, only: %i[]
  resources :services, only: %i[]
  resources :shop_visits, only: %i[]
  resources :shops, only: %i[]
end

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        cars#index
#                                  cars GET    /cars(.:format)                                                                          cars#index
#                               new_car GET    /cars/new(.:format)                                                                      cars#new
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id             :bigint           not null, primary key
#  city           :string
#  name           :string
#  phone_number   :string
#  state          :string
#  street_address :string
#  zip_code       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Shop < ApplicationRecord
  has_many :shop_visits, dependent: :destroy
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy]

  # GET /shops
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  def show; end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit; end

  # POST /shops
  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      redirect_to @shop, notice: "Shop was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /shops/1
  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: "Shop was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /shops/1
  def destroy
    @shop.destroy
    redirect_to shops_url, notice: "Shop was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = Shop.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def shop_params
    params.require(:shop).permit(:name, :street_address, :city, :state, :zip_code, :phone_number)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Shop #<%= shop.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= shop.name %></dd>

      <dt>Street address</dt>
      <dd><%= shop.street_address %></dd>

      <dt>City</dt>
      <dd><%= shop.city %></dd>

      <dt>State</dt>
      <dd><%= shop.state %></dd>

      <dt>Zip code</dt>
      <dd><%= shop.zip_code %></dd>

      <dt>Phone number</dt>
      <dd><%= shop.phone_number %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back shop, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_shop_url(shop), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to shop, method: :delete, data: { confirm: "Do you really want to delete this shop?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(shop.updated_at) %> ago
  </div>
</div>

app/views/shops/_form.html.erb
<% was_validated = shop.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(shop, html: form_html_options) do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = shop.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>

    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% shop.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% street_address_class = "form-control" %>
    <% street_address_was_invalid = shop.errors.include?(:street_address) %>

    <% if was_validated %>
      <% if street_address_was_invalid %>
        <% street_address_class << " is-invalid" %>
      <% else %>
        <% street_address_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :street_address %>

    <%= f.text_field :street_address, class: street_address_class, placeholder: "Enter street address" %>
    <% if street_address_was_invalid %>
      <% shop.errors.full_messages_for(:street_address).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% city_class = "form-control" %>
    <% city_was_invalid = shop.errors.include?(:city) %>

    <% if was_validated %>
      <% if city_was_invalid %>
        <% city_class << " is-invalid" %>
      <% else %>
        <% city_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :city %>

    <%= f.text_field :city, class: city_class, placeholder: "Enter city" %>
    <% if city_was_invalid %>
      <% shop.errors.full_messages_for(:city).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% state_class = "form-control" %>
    <% state_was_invalid = shop.errors.include?(:state) %>

    <% if was_validated %>
      <% if state_was_invalid %>
        <% state_class << " is-invalid" %>
      <% else %>
        <% state_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :state %>

    <%= f.text_field :state, class: state_class, placeholder: "Enter state" %>
    <% if state_was_invalid %>
      <% shop.errors.full_messages_for(:state).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% zip_code_class = "form-control" %>
    <% zip_code_was_invalid = shop.errors.include?(:zip_code) %>

    <% if was_validated %>
      <% if zip_code_was_invalid %>
        <% zip_code_class << " is-invalid" %>
      <% else %>
        <% zip_code_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :zip_code %>

    <%= f.number_field :zip_code, class: zip_code_class, placeholder: "Enter zip code" %>
    <% if zip_code_was_invalid %>
      <% shop.errors.full_messages_for(:zip_code).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% phone_number_class = "form-control" %>
    <% phone_number_was_invalid = shop.errors.include?(:phone_number) %>

    <% if was_validated %>
      <% if phone_number_was_invalid %>
        <% phone_number_class << " is-invalid" %>
      <% else %>
        <% phone_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :phone_number %>

    <%= f.text_field :phone_number, class: phone_number_class, placeholder: "Enter phone number" %>
    <% if phone_number_was_invalid %>
      <% shop.errors.full_messages_for(:phone_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/shops/_list_item.html.erb
<%= link_to shop, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Shop #<%= shop.id %>

    <small class="text-muted">
      <%= time_ago_in_words(shop.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/shops/_table_row.html.erb
<tr>
  <td>
    <%= shop.name %>
  </td>

  <td>
    <%= shop.street_address %>
  </td>

  <td>
    <%= shop.city %>
  </td>

  <td>
    <%= shop.state %>
  </td>

  <td>
    <%= shop.zip_code %>
  </td>

  <td>
    <%= shop.phone_number %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to shop, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_shop_url(shop), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to shop, method: :delete, data: { confirm: "Do you really want to delete this shop?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/shops/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Shop #<%= @shop.id %>
      </h2>

      <div class="card-body">
        <%= render "form", shop: @shop %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Shops

      <%= link_to new_shop_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Name
            </th>

            <th>
              Street address
            </th>

            <th>
              City
            </th>

            <th>
              State
            </th>

            <th>
              Zip code
            </th>

            <th>
              Phone number
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @shops, partial: "table_row", as: :shop %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @shops.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :shop %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Shops

        <%= link_to new_shop_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @shops, partial: "list_item", as: :shop %>
      </div>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Shop
      </h2>

      <div class="card-body">
        <%= render "form", shop: @shop %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @shop, partial: "card", as: :shop %>
  </div>
</div>