config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "cars#index"
  resources :cars, only: %i[index new create show edit]
  resources :documents, only: %i[]
  resources :parts, only: %i[]
  resources :services, only: %i[]
  resources :shop_visits, only: %i[]
  resources :shops, only: %i[]
end

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                                  root GET    /                                                                                        cars#index
#                                  cars GET    /cars(.:format)                                                                          cars#index
#                               new_car GET    /cars/new(.:format)                                                                      cars#new
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id         :bigint           not null, primary key
#  make       :string
#  model      :string
#  name       :string
#  year       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_cars_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Car < ApplicationRecord
  belongs_to :user
  has_many :shop_visits, dependent: :destroy
  has_many :parts, dependent: :destroy
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]

  # GET /cars
  def index
    @cars = current_user.cars
  end

  # GET /cars/1
  def show; end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit; end

  # POST /cars
  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to @car, notice: "Car was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      redirect_to @car, notice: "Car was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
    redirect_to cars_url, notice: "Car was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def car_params
    params.require(:car).permit(:name, :make, :model, :year)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Car #<%= car.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= car.name %></dd>

      <dt>Make</dt>
      <dd><%= car.make %></dd>

      <dt>Model</dt>
      <dd><%= car.model %></dd>

      <dt>Year</dt>
      <dd><%= car.year %></dd>

      <dt>User</dt>
      <dd><%= car.user %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back car, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_car_url(car), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to car, method: :delete, data: { confirm: "Do you really want to delete this car?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(car.updated_at) %> ago
  </div>
</div>

app/views/cars/_form.html.erb
<% was_validated = car.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(car, html: form_html_options) do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = car.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>

    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% car.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% make_class = "form-control" %>
    <% make_was_invalid = car.errors.include?(:make) %>

    <% if was_validated %>
      <% if make_was_invalid %>
        <% make_class << " is-invalid" %>
      <% else %>
        <% make_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :make %>

    <%= f.text_field :make, class: make_class, placeholder: "Enter make" %>
    <% if make_was_invalid %>
      <% car.errors.full_messages_for(:make).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% model_class = "form-control" %>
    <% model_was_invalid = car.errors.include?(:model) %>

    <% if was_validated %>
      <% if model_was_invalid %>
        <% model_class << " is-invalid" %>
      <% else %>
        <% model_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :model %>

    <%= f.text_field :model, class: model_class, placeholder: "Enter model" %>
    <% if model_was_invalid %>
      <% car.errors.full_messages_for(:model).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% year_class = "form-control" %>
    <% year_was_invalid = car.errors.include?(:year) %>

    <% if was_validated %>
      <% if year_was_invalid %>
        <% year_class << " is-invalid" %>
      <% else %>
        <% year_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :year %>

    <%= f.text_field :year, class: year_class, placeholder: "Enter year" %>
    <% if year_was_invalid %>
      <% car.errors.full_messages_for(:year).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>


  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/cars/_list_item.html.erb
<%= link_to car, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Car #<%= car.id %>

    <small class="text-muted">
      <%= time_ago_in_words(car.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/cars/_table_row.html.erb
<tr>
  <td>
    <%= car.name %>
  </td>

  <td>
    <%= car.make %>
  </td>

  <td>
    <%= car.model %>
  </td>

  <td>
    <%= car.year %>
  </td>

  <td>
    <%= car.user %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to car, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_car_url(car), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to car, method: :delete, data: { confirm: "Do you really want to delete this car?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fad fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/cars/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Car #<%= @car.id %>
      </h2>

      <div class="card-body">
        <%= render "form", car: @car %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Cars

      <%= link_to new_car_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Name
            </th>

            <th>
              Make
            </th>

            <th>
              Model
            </th>

            <th>
              Year
            </th>

            <th>
              User
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @cars, partial: "table_row", as: :car %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @cars.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :car %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Cars

        <%= link_to new_car_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @cars, partial: "list_item", as: :car %>
      </div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Car
      </h2>

      <div class="card-body">
        <%= render "form", car: @car %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @car, partial: "card", as: :car %>
  </div>
</div>